2024-01-22 02:15:49,949 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Mon, 22 Jan 2024 02:15:49 +0000. Up 15.48 seconds.
2024-01-22 02:15:49,949 - main.py[DEBUG]: No kernel command line url found.
2024-01-22 02:15:49,950 - main.py[DEBUG]: Closing stdin.
2024-01-22 02:15:49,951 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-01-22 02:15:49,952 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-22 02:15:49,961 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-01-22 02:15:49,981 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-22 02:15:49,985 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-01-22 02:15:49,986 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-22 02:15:49,992 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-01-22 02:15:49,993 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-22 02:15:50,021 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-01-22 02:15:50,022 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-01-22 02:15:50,032 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-01-22 02:15:50,032 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-22 02:15:50,069 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-01-22 02:15:50,070 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-22 02:15:50,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-01-22 02:15:50,099 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-22 02:15:50,131 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-01-22 02:15:50,132 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-01-22 02:15:50,164 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-01-22 02:15:50,165 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-01-22 02:15:50,166 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-01-22 02:15:50,167 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-01-22 02:15:50,167 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-01-22 02:15:50,169 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-01-22 02:15:50,170 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-01-22 02:15:50,185 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-01-22 02:15:50,185 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-01-22 02:15:50,187 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-01-22 02:15:50,188 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-01-22 02:15:50,189 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:50,195 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:50,205 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-01-22 02:15:50,222 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-01-22 02:15:50,275 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-01-22 02:15:50,276 - stages.py[DEBUG]: no cache found
2024-01-22 02:15:50,276 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-01-22 02:15:50,276 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-01-22 02:15:50,288 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-22 02:15:50,289 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-01-22 02:15:50,294 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-01-22 02:15:50,295 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-01-22 02:15:50,295 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-01-22 02:15:50,295 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-01-22 02:15:50,295 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-01-22 02:15:50,295 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-01-22 02:15:50,295 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-01-22 02:15:50,295 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-01-22 02:15:50,295 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-01-22 02:15:50,296 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-01-22 02:15:50,296 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-01-22 02:15:50,296 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-01-22 02:15:50,296 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-01-22 02:15:50,296 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-01-22 02:15:50,296 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-01-22 02:15:50,297 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-01-22 02:15:50,307 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-01-22 02:15:50,307 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-01-22 02:15:50,308 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,315 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-01-22 02:15:50,315 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-01-22 02:15:50,315 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,327 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2405b) after 1 attempts
2024-01-22 02:15:50,327 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,337 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 318b) after 1 attempts
2024-01-22 02:15:50,337 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,347 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-01-22 02:15:50,347 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,357 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-01-22 02:15:50,357 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,367 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-01-22 02:15:50,367 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,377 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-01-22 02:15:50,377 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,379 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-01-22 02:15:50,380 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,382 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-01-22 02:15:50,383 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,391 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-01-22 02:15:50,391 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,393 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-01-22 02:15:50,393 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,396 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 196b) after 1 attempts
2024-01-22 02:15:50,396 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,398 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-01-22 02:15:50,398 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,405 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-01-22 02:15:50,405 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,415 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-01-22 02:15:50,416 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,425 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-01-22 02:15:50,426 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,435 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-01-22 02:15:50,436 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,438 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-01-22 02:15:50,438 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,441 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-01-22 02:15:50,441 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,445 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-01-22 02:15:50,445 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,448 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ (200, 230b) after 1 attempts
2024-01-22 02:15:50,448 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,455 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/ (200, 13b) after 1 attempts
2024-01-22 02:15:50,455 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/3.231.116.115' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/3.231.116.115', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,458 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/ipv4-associations/3.231.116.115 (200, 13b) after 1 attempts
2024-01-22 02:15:50,458 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,461 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/device-number (200, 1b) after 1 attempts
2024-01-22 02:15:50,461 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,465 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/interface-id (200, 21b) after 1 attempts
2024-01-22 02:15:50,466 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,469 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-hostname (200, 29b) after 1 attempts
2024-01-22 02:15:50,469 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,475 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/local-ipv4s (200, 13b) after 1 attempts
2024-01-22 02:15:50,476 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,478 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/mac (200, 17b) after 1 attempts
2024-01-22 02:15:50,478 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,481 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/owner-id (200, 12b) after 1 attempts
2024-01-22 02:15:50,482 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,495 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-hostname (200, 41b) after 1 attempts
2024-01-22 02:15:50,496 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,499 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/public-ipv4s (200, 13b) after 1 attempts
2024-01-22 02:15:50,499 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,503 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-group-ids (200, 20b) after 1 attempts
2024-01-22 02:15:50,503 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,515 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/security-groups (200, 56b) after 1 attempts
2024-01-22 02:15:50,516 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,518 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-id (200, 24b) after 1 attempts
2024-01-22 02:15:50,519 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,521 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2024-01-22 02:15:50,522 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,525 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-id (200, 21b) after 1 attempts
2024-01-22 02:15:50,525 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,528 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-01-22 02:15:50,528 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,531 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:45:ac:40:6c:51/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-01-22 02:15:50,531 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,534 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-01-22 02:15:50,534 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,547 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2024-01-22 02:15:50,547 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,550 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-01-22 02:15:50,550 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,555 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2024-01-22 02:15:50,556 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,558 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/ (200, 18b) after 1 attempts
2024-01-22 02:15:50,558 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,561 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key (200, 398b) after 1 attempts
2024-01-22 02:15:50,561 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,565 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-01-22 02:15:50,565 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,568 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-01-22 02:15:50,568 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,570 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-01-22 02:15:50,570 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,575 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-01-22 02:15:50,575 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,578 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-01-22 02:15:50,579 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,581 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-01-22 02:15:50,581 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,583 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 29b) after 1 attempts
2024-01-22 02:15:50,583 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,597 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-01-22 02:15:50,597 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,600 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-01-22 02:15:50,600 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,602 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-01-22 02:15:50,602 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,615 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-01-22 02:15:50,615 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,618 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 29b) after 1 attempts
2024-01-22 02:15:50,618 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,620 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2024-01-22 02:15:50,620 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,625 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-01-22 02:15:50,625 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,627 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-01-22 02:15:50,628 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,630 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 41b) after 1 attempts
2024-01-22 02:15:50,630 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,635 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-01-22 02:15:50,635 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,637 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-01-22 02:15:50,638 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,640 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2024-01-22 02:15:50,640 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,645 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-01-22 02:15:50,645 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,647 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2024-01-22 02:15:50,648 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,650 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1167b) after 1 attempts
2024-01-22 02:15:50,650 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,655 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1487b) after 1 attempts
2024-01-22 02:15:50,655 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-01-22 02:15:50,658 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-01-22 02:15:50,658 - util.py[DEBUG]: Crawl of metadata service took 0.362 seconds
2024-01-22 02:15:50,662 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-01-22 02:15:50,662 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-01-22 02:15:50,663 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-01-22 02:15:50,664 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-01-22 02:15:50,665 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpnvcksmbc) - w: [600] 12794 bytes/chars
2024-01-22 02:15:50,666 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpjkjpbsqj) - w: [644] 8652 bytes/chars
2024-01-22 02:15:50,667 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-01-22 02:15:50,667 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-01-22 02:15:50,667 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-22 02:15:50,667 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-22 02:15:50,667 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,692 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-22 02:15:50,692 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-22 02:15:50,692 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,694 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-22 02:15:50,694 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-22 02:15:50,694 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,707 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-22 02:15:50,707 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-22 02:15:50,707 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,715 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-22 02:15:50,716 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-22 02:15:50,716 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,719 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-22 02:15:50,719 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,719 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-22 02:15:50,720 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-01-22 02:15:50,720 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0d7153ef103a4ee9e'
2024-01-22 02:15:50,721 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e (recursive=True)
2024-01-22 02:15:50,727 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/handlers (recursive=False)
2024-01-22 02:15:50,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e (recursive=True)
2024-01-22 02:15:50,747 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/scripts (recursive=False)
2024-01-22 02:15:50,749 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e (recursive=True)
2024-01-22 02:15:50,762 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem (recursive=False)
2024-01-22 02:15:50,763 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0d7153ef103a4ee9e/datasource (quiet=False)
2024-01-22 02:15:50,763 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/datasource - wb: [644] 29 bytes
2024-01-22 02:15:50,764 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/datasource (recursive=False)
2024-01-22 02:15:50,775 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/datasource (recursive=False)
2024-01-22 02:15:50,776 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-01-22 02:15:50,777 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-01-22 02:15:50,778 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-01-22 02:15:50,779 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-01-22 02:15:50,779 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-01-22 02:15:50,779 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-01-22 02:15:50,780 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-01-22 02:15:50,781 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-01-22 02:15:50,781 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-01-22 02:15:50,782 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-01-22 02:15:50,782 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-01-22 02:15:50,783 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-01-22 02:15:50,784 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-01-22 02:15:50,795 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-01-22 02:15:50,797 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12902 bytes
2024-01-22 02:15:50,798 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/obj.pkl (recursive=False)
2024-01-22 02:15:50,799 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/obj.pkl (recursive=False)
2024-01-22 02:15:50,800 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0d7153ef103a4ee9e. new=True
2024-01-22 02:15:50,800 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-22 02:15:50,800 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-22 02:15:50,800 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,825 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-22 02:15:50,825 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-22 02:15:50,825 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,826 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-22 02:15:50,826 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-22 02:15:50,826 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,829 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-22 02:15:50,829 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-22 02:15:50,829 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,845 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-22 02:15:50,846 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-22 02:15:50,846 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,848 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-22 02:15:50,848 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,848 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-22 02:15:50,850 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-01-22 02:15:50,850 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-01-22 02:15:50,850 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-22 02:15:50,850 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-22 02:15:50,850 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-01-22 02:15:50,850 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-01-22 02:15:50,851 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-22 02:15:50,851 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-22 02:15:50,851 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-01-22 02:15:50,851 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-01-22 02:15:50,851 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-01-22 02:15:50,851 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-01-22 02:15:50,851 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-01-22 02:15:50,851 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-01-22 02:15:50,851 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-01-22 02:15:50,851 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-01-22 02:15:50,851 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-01-22 02:15:50,852 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-01-22 02:15:50,852 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-01-22 02:15:50,852 - stages.py[DEBUG]: network config disabled by system_cfg
2024-01-22 02:15:50,853 - stages.py[INFO]: network config is disabled by system_cfg
2024-01-22 02:15:50,853 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-01-22 02:15:50,853 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-01-22 02:15:50,853 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt - wb: [600] 2405 bytes
2024-01-22 02:15:50,854 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt (recursive=False)
2024-01-22 02:15:50,855 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt (recursive=False)
2024-01-22 02:15:50,857 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:50,866 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt.i - wb: [600] 2427 bytes
2024-01-22 02:15:50,867 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt.i (recursive=False)
2024-01-22 02:15:50,868 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/user-data.txt.i (recursive=False)
2024-01-22 02:15:50,869 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt - wb: [600] 0 bytes
2024-01-22 02:15:50,870 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt (recursive=False)
2024-01-22 02:15:50,871 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt (recursive=False)
2024-01-22 02:15:50,872 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt.i - wb: [600] 308 bytes
2024-01-22 02:15:50,873 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt.i (recursive=False)
2024-01-22 02:15:50,885 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data.txt.i (recursive=False)
2024-01-22 02:15:50,885 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt - wb: [600] 0 bytes
2024-01-22 02:15:50,887 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt (recursive=False)
2024-01-22 02:15:50,888 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt (recursive=False)
2024-01-22 02:15:50,890 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt.i - wb: [600] 308 bytes
2024-01-22 02:15:50,890 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt.i (recursive=False)
2024-01-22 02:15:50,891 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/vendor-data2.txt.i (recursive=False)
2024-01-22 02:15:50,893 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-22 02:15:50,894 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-21-149.ec2.internal (ip-172-31-21-149)
2024-01-22 02:15:50,894 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-21-149.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:51,113 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-21-149.ec2.internal
2024-01-22 02:15:51,113 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-21-149.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:51,121 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpvrr86nmr) - w: [644] 78 bytes/chars
2024-01-22 02:15:51,122 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/consume_data - wb: [644] 24 bytes
2024-01-22 02:15:51,123 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/consume_data (recursive=False)
2024-01-22 02:15:51,126 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/consume_data (recursive=False)
2024-01-22 02:15:51,127 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/consume_data'>)
2024-01-22 02:15:51,128 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-01-22 02:15:51,128 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-01-22 02:15:51,129 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-01-22 02:15:51,130 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-01-22 02:15:51,130 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-01-22 02:15:51,130 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,130 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,130 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,131 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,131 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,131 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-01-22 02:15:51,131 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-01-22 02:15:51,131 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-01-22 02:15:51,131 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,133 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-01-22 02:15:51,134 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-01-22 02:15:51,134 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-01-22 02:15:51,134 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1756 bytes
2024-01-22 02:15:51,145 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/scripts/user-data.txt (recursive=False)
2024-01-22 02:15:51,146 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/scripts/user-data.txt (recursive=False)
2024-01-22 02:15:51,147 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-01-22 02:15:51,148 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/cloud-config.txt - wb: [600] 154 bytes
2024-01-22 02:15:51,149 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/cloud-config.txt (recursive=False)
2024-01-22 02:15:51,150 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/cloud-config.txt (recursive=False)
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-01-22 02:15:51,151 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-01-22 02:15:51,151 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-01-22 02:15:51,151 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-01-22 02:15:51,152 - stages.py[DEBUG]: no vendordata from datasource
2024-01-22 02:15:51,152 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-01-22 02:15:51,152 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-01-22 02:15:51,152 - stages.py[DEBUG]: no vendordata2 from datasource
2024-01-22 02:15:51,152 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-01-22 02:15:51,152 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-01-22 02:15:51,152 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-01-22 02:15:51,152 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,176 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-01-22 02:15:51,177 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-01-22 02:15:51,177 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,178 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-01-22 02:15:51,178 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-01-22 02:15:51,178 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,181 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-01-22 02:15:51,181 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-01-22 02:15:51,181 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,198 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-01-22 02:15:51,198 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-01-22 02:15:51,198 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,201 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-01-22 02:15:51,201 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,201 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-01-22 02:15:51,202 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-01-22 02:15:51,202 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-01-22 02:15:51,202 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,204 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,204 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,797 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-01-22 02:15:51,797 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-01-22 02:15:51,797 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-01-22 02:15:51,803 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-01-22 02:15:51,814 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 17006 bytes
2024-01-22 02:15:51,816 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/obj.pkl (recursive=False)
2024-01-22 02:15:51,818 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/obj.pkl (recursive=False)
2024-01-22 02:15:51,818 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-01-22 02:15:51,819 - main.py[DEBUG]: no di_report found in config.
2024-01-22 02:15:51,821 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,821 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,835 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,835 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,839 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,840 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,843 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,843 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,854 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,855 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,858 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,858 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,865 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,865 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,877 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,877 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,881 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,881 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,894 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,895 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,897 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,898 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,901 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,901 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,904 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,905 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,910 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,910 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,917 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,917 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,921 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:51,921 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:51,924 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-22 02:15:51,925 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-01-22 02:15:51,926 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-01-22 02:15:51,926 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9df0>)
2024-01-22 02:15:51,926 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-01-22 02:15:51,926 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-01-22 02:15:51,926 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-01-22 02:15:51,927 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-01-22 02:15:51,927 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_seed_random - wb: [644] 25 bytes
2024-01-22 02:15:51,927 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_seed_random (recursive=False)
2024-01-22 02:15:51,929 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_seed_random (recursive=False)
2024-01-22 02:15:51,929 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_seed_random'>)
2024-01-22 02:15:51,929 - cc_seed_random.py[DEBUG]: no command provided
2024-01-22 02:15:51,929 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-01-22 02:15:51,930 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-01-22 02:15:51,930 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-01-22 02:15:51,930 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9df0>)
2024-01-22 02:15:51,930 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-01-22 02:15:51,930 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-01-22 02:15:51,930 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-01-22 02:15:51,930 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-01-22 02:15:51,931 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_files - wb: [644] 25 bytes
2024-01-22 02:15:51,931 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_files (recursive=False)
2024-01-22 02:15:51,932 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_files (recursive=False)
2024-01-22 02:15:51,933 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_files'>)
2024-01-22 02:15:51,933 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-01-22 02:15:51,933 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-01-22 02:15:51,933 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-01-22 02:15:51,933 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-01-22 02:15:51,934 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_metadata - wb: [644] 25 bytes
2024-01-22 02:15:51,944 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_metadata (recursive=False)
2024-01-22 02:15:51,946 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_metadata (recursive=False)
2024-01-22 02:15:51,946 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_write_metadata'>)
2024-01-22 02:15:51,947 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2024-01-22 02:15:51,950 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-01-22 02:15:51,951 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-01-22 02:15:51,952 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-01-22 02:15:51,952 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-01-22 02:15:51,952 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-01-22 02:15:51,953 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-01-22 02:15:51,954 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-01-22 02:15:51,954 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-01-22 02:15:51,954 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-01-22 02:15:51,954 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-01-22 02:15:51,954 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9ee0>)
2024-01-22 02:15:51,954 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-01-22 02:15:51,955 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,020 - util.py[DEBUG]: Reading from /proc/1413/mountinfo (quiet=False)
2024-01-22 02:15:52,020 - util.py[DEBUG]: Read 2930 bytes from /proc/1413/mountinfo
2024-01-22 02:15:52,021 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-01-22 02:15:52,021 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-01-22 02:15:52,021 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-01-22 02:15:52,021 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-01-22 02:15:52,022 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,161 - util.py[DEBUG]: resize_devices took 0.141 seconds
2024-01-22 02:15:52,162 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-01-22 02:15:52,162 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-01-22 02:15:52,162 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-01-22 02:15:52,162 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-01-22 02:15:52,162 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9fa0>)
2024-01-22 02:15:52,162 - util.py[DEBUG]: Reading from /proc/1413/mountinfo (quiet=False)
2024-01-22 02:15:52,163 - util.py[DEBUG]: Read 2930 bytes from /proc/1413/mountinfo
2024-01-22 02:15:52,163 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-01-22 02:15:52,163 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-01-22 02:15:52,165 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,167 - util.py[DEBUG]: Forked child 1564 who will run callback log_time
2024-01-22 02:15:52,168 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-01-22 02:15:52,168 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-01-22 02:15:52,168 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-01-22 02:15:52,169 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-01-22 02:15:52,169 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_disk_setup - wb: [644] 25 bytes
2024-01-22 02:15:52,171 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_disk_setup (recursive=False)
2024-01-22 02:15:52,173 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_disk_setup (recursive=False)
2024-01-22 02:15:52,173 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_disk_setup'>)
2024-01-22 02:15:52,174 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-01-22 02:15:52,174 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-01-22 02:15:52,174 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-01-22 02:15:52,185 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_mounts - wb: [644] 25 bytes
2024-01-22 02:15:52,185 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_mounts (recursive=False)
2024-01-22 02:15:52,187 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_mounts (recursive=False)
2024-01-22 02:15:52,187 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_mounts'>)
2024-01-22 02:15:52,188 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-01-22 02:15:52,188 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-01-22 02:15:52,188 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-01-22 02:15:52,188 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-01-22 02:15:52,188 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-01-22 02:15:52,188 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-01-22 02:15:52,188 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-01-22 02:15:52,188 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-01-22 02:15:52,188 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-01-22 02:15:52,189 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-01-22 02:15:52,189 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-01-22 02:15:52,189 - cc_mounts.py[DEBUG]: no need to setup swap
2024-01-22 02:15:52,189 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-01-22 02:15:52,189 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-01-22 02:15:52,189 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-01-22 02:15:52,189 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-01-22 02:15:52,189 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3c4e50>)
2024-01-22 02:15:52,189 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-01-22 02:15:52,190 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/data/set-hostname
2024-01-22 02:15:52,190 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-01-22 02:15:52,190 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-01-22 02:15:52,190 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-01-22 02:15:52,190 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-01-22 02:15:52,190 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9fa0>)
2024-01-22 02:15:52,190 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-21-149.ec2.internal (ip-172-31-21-149)
2024-01-22 02:15:52,190 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,195 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-21-149.ec2.internal in 1 files
2024-01-22 02:15:52,195 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 29 bytes
2024-01-22 02:15:52,196 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-01-22 02:15:52,198 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-01-22 02:15:52,198 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-01-22 02:15:52,198 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-01-22 02:15:52,199 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-01-22 02:15:52,199 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f2c0e3a9df0>)
2024-01-22 02:15:52,199 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-01-22 02:15:52,199 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-01-22 02:15:52,199 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-01-22 02:15:52,199 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-01-22 02:15:52,200 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ca_certs - wb: [644] 25 bytes
2024-01-22 02:15:52,200 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ca_certs (recursive=False)
2024-01-22 02:15:52,202 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ca_certs (recursive=False)
2024-01-22 02:15:52,202 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ca_certs'>)
2024-01-22 02:15:52,202 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-01-22 02:15:52,202 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-01-22 02:15:52,202 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-01-22 02:15:52,203 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-01-22 02:15:52,203 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_rsyslog - wb: [644] 24 bytes
2024-01-22 02:15:52,204 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_rsyslog (recursive=False)
2024-01-22 02:15:52,218 - util.py[DEBUG]: backgrounded Resizing took 0.053 seconds
2024-01-22 02:15:52,225 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_rsyslog (recursive=False)
2024-01-22 02:15:52,226 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_rsyslog'>)
2024-01-22 02:15:52,226 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-01-22 02:15:52,226 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-01-22 02:15:52,226 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-01-22 02:15:52,226 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-01-22 02:15:52,227 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_selinux - wb: [644] 24 bytes
2024-01-22 02:15:52,227 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_selinux (recursive=False)
2024-01-22 02:15:52,228 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_selinux (recursive=False)
2024-01-22 02:15:52,229 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_selinux'>)
2024-01-22 02:15:52,247 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-01-22 02:15:52,247 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-01-22 02:15:52,247 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-01-22 02:15:52,248 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-01-22 02:15:52,248 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-01-22 02:15:52,248 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-01-22 02:15:52,248 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-01-22 02:15:52,248 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-01-22 02:15:52,249 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_users_groups - wb: [644] 23 bytes
2024-01-22 02:15:52,250 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_users_groups (recursive=False)
2024-01-22 02:15:52,252 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_users_groups (recursive=False)
2024-01-22 02:15:52,252 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_users_groups'>)
2024-01-22 02:15:52,265 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-01-22 02:15:52,265 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,365 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-01-22 02:15:52,391 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-01-22 02:15:52,393 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-01-22 02:15:52,393 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-01-22 02:15:52,420 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-01-22 02:15:52,421 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-01-22 02:15:52,421 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-01-22 02:15:52,421 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-01-22 02:15:52,422 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ssh - wb: [644] 25 bytes
2024-01-22 02:15:52,422 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ssh (recursive=False)
2024-01-22 02:15:52,424 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ssh (recursive=False)
2024-01-22 02:15:52,424 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ssh'>)
2024-01-22 02:15:52,425 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,447 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-01-22 02:15:52,465 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:52,487 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-01-22 02:15:52,506 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-01-22 02:15:52,506 - util.py[DEBUG]: Read 116 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-01-22 02:15:52,506 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-01-22 02:15:52,506 - util.py[DEBUG]: Read 196 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-01-22 02:15:52,507 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-22 02:15:52,528 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-22 02:15:52,529 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-01-22 02:15:52,530 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-01-22 02:15:52,531 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-22 02:15:52,531 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,532 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,532 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-01-22 02:15:52,532 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-01-22 02:15:52,532 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-01-22 02:15:52,532 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 398 bytes
2024-01-22 02:15:52,532 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,533 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,533 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-01-22 02:15:52,544 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-22 02:15:52,544 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-22 02:15:52,545 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-01-22 02:15:52,547 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-01-22 02:15:52,548 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,548 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,548 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-01-22 02:15:52,548 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-01-22 02:15:52,549 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-01-22 02:15:52,549 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 564 bytes
2024-01-22 02:15:52,549 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,549 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-01-22 02:15:52,549 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-01-22 02:15:52,551 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-01-22 02:15:52,551 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-01-22 02:15:52,552 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpove8l1tq) - w: [644] 486 bytes/chars
2024-01-22 02:15:52,552 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-01-22 02:15:52,552 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-01-22 02:15:52,552 - util.py[DEBUG]: cloud-init mode 'init' took 2.845 seconds (2.84)
2024-01-22 02:15:52,553 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-01-22 02:15:53,540 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Mon, 22 Jan 2024 02:15:53 +0000. Up 18.99 seconds.
2024-01-22 02:15:53,546 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,547 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,554 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,555 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,565 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,565 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,568 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,568 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,575 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,575 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,578 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,578 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,584 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,585 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,590 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,590 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,609 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,610 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,612 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:53,613 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:53,615 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-22 02:15:53,616 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-01-22 02:15:53,616 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-01-22 02:15:53,616 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-01-22 02:15:53,616 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_keyboard - wb: [644] 25 bytes
2024-01-22 02:15:53,619 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_keyboard (recursive=False)
2024-01-22 02:15:53,623 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_keyboard (recursive=False)
2024-01-22 02:15:53,623 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_keyboard'>)
2024-01-22 02:15:53,623 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-01-22 02:15:53,623 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-01-22 02:15:53,624 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-01-22 02:15:53,624 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-01-22 02:15:53,624 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_locale - wb: [644] 24 bytes
2024-01-22 02:15:53,635 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_locale (recursive=False)
2024-01-22 02:15:53,636 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_locale (recursive=False)
2024-01-22 02:15:53,637 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_locale'>)
2024-01-22 02:15:53,637 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-01-22 02:15:53,637 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-01-22 02:15:53,637 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-01-22 02:15:53,637 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-01-22 02:15:53,637 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-01-22 02:15:53,638 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-01-22 02:15:53,646 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-01-22 02:15:53,649 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-01-22 02:15:53,650 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-01-22 02:15:53,650 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-01-22 02:15:53,650 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-01-22 02:15:53,650 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_set_passwords - wb: [644] 24 bytes
2024-01-22 02:15:53,651 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_set_passwords (recursive=False)
2024-01-22 02:15:53,652 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_set_passwords (recursive=False)
2024-01-22 02:15:53,653 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_set_passwords'>)
2024-01-22 02:15:53,653 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-01-22 02:15:53,685 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-01-22 02:15:53,686 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-01-22 02:15:53,686 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-01-22 02:15:53,686 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-01-22 02:15:53,686 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-01-22 02:15:53,686 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-01-22 02:15:53,687 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-01-22 02:15:53,687 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_variables - wb: [644] 25 bytes
2024-01-22 02:15:53,688 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_variables (recursive=False)
2024-01-22 02:15:53,690 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_variables (recursive=False)
2024-01-22 02:15:53,690 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_variables'>)
2024-01-22 02:15:53,690 - cc_yum_variables.py[INFO]: handling yum-variables
2024-01-22 02:15:53,690 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.3, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-01-22 02:15:53,691 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-01-22 02:15:53,691 - cc_yum_variables.py[INFO]: No yum vars to set
2024-01-22 02:15:53,691 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-01-22 02:15:53,691 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-01-22 02:15:53,691 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-01-22 02:15:53,691 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-01-22 02:15:53,692 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_add_repo (recursive=False)
2024-01-22 02:15:53,693 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_add_repo (recursive=False)
2024-01-22 02:15:53,694 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_yum_add_repo'>)
2024-01-22 02:15:53,694 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-01-22 02:15:53,694 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-01-22 02:15:53,694 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-01-22 02:15:53,704 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-01-22 02:15:53,705 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ntp - wb: [644] 24 bytes
2024-01-22 02:15:53,705 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ntp (recursive=False)
2024-01-22 02:15:53,707 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ntp (recursive=False)
2024-01-22 02:15:53,707 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_ntp'>)
2024-01-22 02:15:53,707 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-01-22 02:15:53,707 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-01-22 02:15:53,707 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-01-22 02:15:53,708 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-01-22 02:15:53,708 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_timezone - wb: [644] 24 bytes
2024-01-22 02:15:53,709 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_timezone (recursive=False)
2024-01-22 02:15:53,710 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_timezone (recursive=False)
2024-01-22 02:15:53,710 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_timezone'>)
2024-01-22 02:15:53,724 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-01-22 02:15:53,725 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-01-22 02:15:53,725 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-01-22 02:15:53,725 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-01-22 02:15:53,725 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb38723a340>)
2024-01-22 02:15:53,725 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-01-22 02:15:53,725 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-01-22 02:15:53,725 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-01-22 02:15:53,725 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-01-22 02:15:53,726 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_runcmd - wb: [644] 25 bytes
2024-01-22 02:15:53,726 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_runcmd (recursive=False)
2024-01-22 02:15:53,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_runcmd (recursive=False)
2024-01-22 02:15:53,728 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0d7153ef103a4ee9e/sem/config_runcmd'>)
2024-01-22 02:15:53,728 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-01-22 02:15:53,728 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-01-22 02:15:53,729 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-01-22 02:15:53,729 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp3m434_vk) - w: [644] 513 bytes/chars
2024-01-22 02:15:53,729 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-01-22 02:15:53,729 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-01-22 02:15:53,730 - util.py[DEBUG]: cloud-init mode 'modules' took 0.415 seconds (0.41)
2024-01-22 02:15:53,730 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-01-22 02:15:54,515 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Mon, 22 Jan 2024 02:15:54 +0000. Up 20.03 seconds.
2024-01-22 02:15:54,525 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-01-22 02:15:54,525 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-01-22 02:15:54,528 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-01-22 02:15:54,529 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-01-22 02:15:54,529 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-01-22 02:15:54,529 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7fa51919ae20>)
2024-01-22 02:15:54,530 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2024-01-22 02:16:22,746 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2024-01-22 02:16:22,746 - main.py[DEBUG]: Ran 1 modules with 0 failures
2024-01-22 02:16:22,747 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp677raey4) - w: [644] 541 bytes/chars
2024-01-22 02:16:22,747 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp3nb4q593) - w: [644] 64 bytes/chars
2024-01-22 02:16:22,748 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-01-22 02:16:22,748 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-01-22 02:16:22,748 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2024-01-22 02:16:22,748 - util.py[DEBUG]: cloud-init mode 'modules' took 28.399 seconds (28.17)
2024-01-22 02:16:22,748 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
